# -*- coding: utf-8 -*-
"""Meu_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/bea-del/4326ed6871ccce37efc8f78c8c77c972/untitled7.ipynb
"""

!pip install langchain langchain-groq langchain-community beautifulsoup4 lxml html5lib

# =========================
# IMPORTA BIBLIOTECAS
# =========================

import os

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate


# =========================
# CHAVE DA API GROQ
# =========================

os.environ["GROQ_API_KEY"] = ""


# =========================
# INICIALIZA MODELO
# =========================

chat = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7
)


# =========================
# PROMPT DO CHATBOT
# =========================

template = ChatPromptTemplate.from_messages([
    (
        "system",
        """
Você é um especialista em filmes e séries da Netflix.

Responda de forma natural, simples e objetiva.

Você pode recomendar séries, filmes,
explicar sinopses e sugerir conteúdos parecidos.
"""
    ),

    (
        "human",
        "{pergunta}"
    )
])


# =========================
# CRIA CHAIN
# =========================

chain = template | chat


# =========================
# LOOP DO CHAT
# =========================

print("Chat Netflix iniciado!")
print("Digite x para sair.\n")


while True:

    pergunta = input("Pergunta: ")

    if pergunta.lower() == "x":
        print("Chat encerrado.")
        break

    try:

        resposta = chain.invoke({
            "pergunta": pergunta
        })

        print("\nResposta:")
        print(resposta.content)

    except Exception as erro:
        print("\nERRO:")
        print(erro)

    print("\n" + "-" * 50 + "\n")